version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: myapp_development
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  app:
    build: 
      context: .
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle install && bundle exec rails s -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: 192.168.18.10
      DB_PORT: 5433
      DB_USERNAME: postgres
      DB_PASSWORD: password
      DATABASE_NAME: myapp_development

volumes:
  db_data:
